# language to be used in Travis Dynamic environment
language: java

addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
  artifacts:
    working_dir: target

# jobs workflow
# build, test and deploy
# usage of external scripts for readability
jobs:
  include:
    - stage: build
      name: Compile
      before_script: echo "BUILD"
      script:
        - sh -e /etc/init.d/xvfb start
        - mvn clean install -DskipTests=true
      after_success: echo "SUCCESS"
      after_failure: echo "FAILURE"
    - stage: test
      name: Run sample tests
      before_script: echo "TEST"
      script: mvn test
      after_script:
        - rm -rf docs/cucumber-html-reports
        - cp target/cucumber-html-reports docs/cucumber-html-reports
      after_success: echo "SUCCESS"
      after_failure: echo "FAILURE"
      addons:
        artifacts:
          working_dir: target/cucumber-html-reports/
    - stage: deploy
      name: Deploy Stable Image
      before_script: echo "DEPLOY"
      script: mvn --settings .m2/settings.xml deploy
      after_success: echo "SUCCESS"
      after_failure: echo "FAILURE"
