# language to be used in Travis Dynamic environment
language: java

addons:
  sonarcloud:
    organization: "esensautomation"
    token:
      secure: "**************************" # encrypted value of your token
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
  artifacts:
    working_dir: target

# jobs workflow
# build, test and deploy
# usage of external scripts for readability
jobs:
  include:
    - stage: build
      name: Compile
      before_script: echo "BUILD"
      script:
        - mvn clean install -DskipTests=true
      after_success: echo "SUCCESS"
      after_failure: echo "FAILURE"

    - stage: test
      name: SonarQube quality gates
      before_script: echo "TEST"
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
      after_script:
        - rm -rf docs/cucumber-html-reports
        - cp target/cucumber-html-reports docs/cucumber-html-reports
      after_success: echo "SUCCESS"
      after_failure: echo "FAILURE"
      addons:
        artifacts:
          working_dir: docs/cucumber-html-reports
    - stage: deploy
      name: Deploy Stable Image
      before_script: echo "DEPLOY"
      script: mvn --settings .m2/settings.xml deploy
      after_success: echo "SUCCESS"
      after_failure: echo "FAILURE"
